<?xml version="1.0"?>
<!DOCTYPE PROFILE [
<!-- Profile: correlates profiling info with program structure. -->
<!ELEMENT PROFILE (PROFILEHDR, PROFILEPARAMS, PROFILESCOPETREE)>
<!ATTLIST PROFILE
	version CDATA #REQUIRED>
  <!ELEMENT PROFILEHDR (#PCDATA)>
  <!ELEMENT PROFILEPARAMS (TARGET, METRICS)>
    <!ELEMENT TARGET EMPTY>
    <!ATTLIST TARGET
	name CDATA #REQUIRED>
    <!ELEMENT METRICS (METRIC)+>
    <!ELEMENT METRIC EMPTY>
    <!ATTLIST METRIC
	shortName   CDATA #REQUIRED
	nativeName  CDATA #REQUIRED
	period      CDATA #REQUIRED
	units       CDATA #IMPLIED
	displayName CDATA #IMPLIED
	display     (true|false) #IMPLIED>
  <!ELEMENT PROFILESCOPETREE (PGM)*>
    <!-- This is essentially the PGM dtd with M element added. -->
    <!ELEMENT PGM (G|LM|F|M)+>
    <!ATTLIST PGM
	n CDATA #REQUIRED>
    <!-- Groups create arbitrary sets of other elements except PGM. -->
    <!ELEMENT G (G|LM|F|P|L|S|M)*>
    <!ATTLIST G
	n CDATA #IMPLIED>
    <!-- Runtime load modules for PGM (e.g., DSOs, exe) -->
    <!ELEMENT LM (G|F|M)*>
    <!ATTLIST LM
	n CDATA #REQUIRED>
    <!-- Files contain procedures and source line info -->
    <!ELEMENT F (G|P|L|S|M)*>
    <!ATTLIST F
	n CDATA #REQUIRED>
    <!-- Procedures contain source line info 
         n: processed name; ln: link name -->
    <!ELEMENT P (G|L|S|M)*>
    <!ATTLIST P
	n  CDATA #REQUIRED
	ln CDATA #IMPLIED
	b CDATA #IMPLIED
	e CDATA #IMPLIED>
    <!-- Loops -->
    <!ELEMENT L (G|L|S|M)*>
    <!ATTLIST L
	b CDATA #IMPLIED
	e CDATA #IMPLIED>
    <!-- Statement/Statement range -->
    <!ELEMENT S (M)*>
    <!ATTLIST S
	b CDATA #REQUIRED
	e CDATA #IMPLIED
	id CDATA #IMPLIED>
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	n CDATA #REQUIRED
	v CDATA #REQUIRED>
]>
<PROFILE version="3.0">
<PROFILEHDR></PROFILEHDR>
<PROFILEPARAMS>
  <TARGET name="example"/>
  <METRICS>
    <METRIC shortName="0" nativeName="PAPI_L1_DCA" displayName="PAPI_L1_DCA" period="32767" units="PAPI events"/>
  </METRICS>
</PROFILEPARAMS>
<PROFILESCOPETREE>
<PGM n="example">
  <LM n="/home/vuduc2/projects/ROSE/tmp/xml/xerces-c/hpctif/examples/data/01/example">
    <F n="./example.c">
      <P n="main">
        <S b="15">
          <M n="0" v="131068"/>
        </S>
        <S b="25">
          <M n="0" v="65534"/>
        </S>
        <S b="26">
          <M n="0" v="65534"/>
        </S>
      </P>
      <P n="mv">
        <S b="61">
          <M n="0" v="65534"/>
        </S>
        <S b="62">
          <M n="0" v="294903"/>
        </S>
      </P>
    </F>
  </LM>
</PGM>
</PROFILESCOPETREE>
</PROFILE>
